### PR TITLE
[PRD-930] Use AMQP heartbeat for mcollective (for 4.0)

### PR DESCRIPTION
**Pull request by warpc**
With new mcollective and stomp this changes available to detect fail connection to RabbitMQ server and automatically reconnect and prevent many problems.

### CODE REVIEW

**Comment by monroid** [comment]
retest this please

**Comment by aglarendil** [comment]
rebase, please on the newest master

**Comment by warpc** [comment]
Rebase to newest master

**Comment by aglarendil** [comment]
+2

**Pull request merged**
