### PR TITLE
Passed zero size disks in pmanager

### PR DESCRIPTION
**Pull request by kozhukalov**

### CODE REVIEW

**Comment by yoojinl** [comment]
+

**Comment by aglarendil** [comment]
pull request system test is not relevant for this change. Could you please confirm that ISO built with this code works fine?

**Comment by adidenko** [comment]
I've tested this change on a live fuel-3.2.1-85 without building iso. It worked OK, I've deployed CentOS env just fine.

**Comment by aglarendil** [comment]
+1

**Pull request merged**
