### PR TITLE
Sync ceph working branch

### PR DESCRIPTION
**Pull request by xarses**
fix multiple issues with ceph deployment.
fix issues with creating bare partitions.

ceph still deploys using ceph/example/site.pp with some tweaking for your env.
Working:
- ceph-mon
- ceph-osd
- ceph-cinder
- centos support

not working
- ceph-glance via horizon (needs some patches)
- glance via cli with --location is broken
- radosgw
- ubuntu support

### CODE REVIEW

**Comment by xdel** [comment]
Please address all the patchwork to the OSCI team.

**Comment by xarses** [comment]
@xdel correct, @angdraug submitted OSC-149 to help resolve the problem

**Comment by mihgen** [comment]
retest this please

**Comment by xarses** [comment]
closing

**Pull request closed without merging**
