### PR TITLE
Added cciss p separator

### PR DESCRIPTION
**Pull request by kozhukalov**

### CODE REVIEW

**Comment by xdel** [comment]
plus one to not getting wrong partition paths

**Comment by kozhukalov** [comment]
what does it mean "plus one to not getting wrong partition paths"?

**Comment by xdel** [comment]
It is on what your fix about.

**Comment by xarses** [comment]
Isn't this the same as https://github.com/Mirantis/fuel/pull/756 ?

**Comment by kozhukalov** [comment]
Yes, it is. Will close.

**Pull request closed without merging**
