### PR TITLE
[PRD-2326] sync ntp during anaconda post as well

### PR DESCRIPTION
**Pull request by mattymo**

### CODE REVIEW

**Comment by mattymo** [comment]
Code is copied from lines 61-63 of %pre. Changes to %pre don't write to software clock of target installed system, but they do help keep logs in sync during install.

**Comment by mihgen** [comment]
+1 for sync time in post section. I don't know what exactly in that snippet though.

**Comment by mattymo** [comment]
ntp_kickstart runs:
ntpdate -t 4 -b $server 
$server is IP of Cobbler server

**Comment by xdel** [comment]
+1

**Comment by aglarendil** [comment]
+2

**Pull request merged**
