### PR TITLE
new options for Havana

### PR DESCRIPTION
**Pull request by xenolog**

### CODE REVIEW

**Comment by angdraug** [comment]
Do we really want to maintain a separate branch for Havana and deal with all the fallout of merging a large feature branch into master at some later point? I think it would be safer to implement Havana-specific changes in a backwards compatible manner and merge them one at a time. That way, everyone is exposed to these changes at the same time and any breakage is detected early and can be fixed quickly and with minimum disruption.

**Comment by xenolog** [comment]
YES. I have some reasons for it:
- quantum renamed to neutron
- some packages requirements different with grizzly
- arrived  new options and deprecated some old.

**Comment by dmitryilyin** [comment]
+1

**Comment by xdel** [comment]
+1

**Pull request merged**
