### PR TITLE
Apache redirect

### PR DESCRIPTION
**Pull request by dmi-try**

### CODE REVIEW

**Comment by xdel** [comment]
It`s time to throw apache out! Can we move master on nginx entirely for not having two webservers?

**Comment by bogdando** [comment]
And it is good time to chmod nginx logs to 640 :-)

**Comment by aglarendil** [comment]
Will be merged into develop after 3.1 release

**Comment by plechenko** [comment]
add to whitelist

retest this please

**Comment by plechenko** [comment]
ok to test

**Pull request closed without merging**
