### PR TITLE
Remove puppet master

### PR DESCRIPTION
**Pull request by warpc**
Should be apply with:
- https://review.openstack.org/#/c/54098/
- https://review.openstack.org/#/c/54100/
- https://review.openstack.org/#/c/54532

### CODE REVIEW

**Comment by mihgen** [comment]
rebase please

**Comment by warpc** [comment]
Rebase.

**Comment by dmitryilyin** [comment]
+1

**Comment by warpc** [comment]
Rebase to newest master

**Comment by aglarendil** [comment]
retest this please

**Comment by warpc** [comment]
retest this please

**Comment by aglarendil** [comment]
+2

**Pull request merged**
