### PR TITLE
257285: Fix satellite connect timeout

### PR DESCRIPTION
**Pull request by mattymo**
wget http://$redhat_management_server/pub/RHN-ORG-TRUSTED-SSL-CERT -O $mycert takes 20 minutes (60s TCP timeout \* 20 retries) if there is DNS resolution but no internet access.

Rewrote Cobbler snippet to set a reasonable timeout if the connection can't be made.
https://bugs.launchpad.net/fuel/+bug/1257285

### CODE REVIEW

**Comment by mihgen** [comment]
How did you test it? Do you have pull request to master as well?

**Comment by mattymo** [comment]
Mike, building iso now. Master request is https://github.com/Mirantis/fuel/pull/900

**Comment by mihgen** [comment]
Any success with ISO?

**Comment by mattymo** [comment]
ISO finally built (locally), but also ready on Jenkins on ISO 89 for 3.2.1
Install with access to Satellite - works
Install with DNS resolution but no access to Internet/Satellite - works (with appropriate errors as expected). no timeout on deploy

**Comment by aglarendil** [comment]
+2

**Pull request merged**
