### PR TITLE
Pick ceph havana

### PR DESCRIPTION
**Pull request by aglarendil**

### CODE REVIEW

**Comment by aglarendil** [comment]
retest this please

**Comment by aglarendil** [comment]
retest this please

**Comment by tleontovich** [comment]
retest this please

**Comment by xarses** [comment]
Should work as it is doesn't pass fuel_syntax_check re-based on master it has same error as master 

"Error: Could not parse for environment production: Syntax error at 'neutron_config'; expected ')' at /home/andreww/git/fuel/deployment/puppet/neutron/manifests/keystone/auth.pp:2"

**Comment by xarses** [comment]
Superseded by #848

**Pull request closed without merging**
