### PR TITLE
Modify ostf.pp

### PR DESCRIPTION
**Pull request by tleontovich**
- Delete nailgun/file/venv-ostf with hardcoded requirements
- Remove block with parsing venv-ostf file dependency
- Replace installtion of two ostf packages for one fuel_ostf

Fixes: OSTF-237

### CODE REVIEW

**Comment by aglarendil** [comment]
+1

Dima P. to review and endorse that we have fuel_ostf package in ISO after ISO is built.

**Comment by dmi-try** [comment]
Packages are missed in iso. Do not accept.

**Comment by dmi-try** [comment]
retest this please

**Comment by dmi-try** [comment]
+1

**Pull request merged**
