### PR TITLE
switch to GPT

### PR DESCRIPTION
**Pull request by xdel**
Get rid of memory waste named crashkernel area. Centos-only (for both master and clients).

### CODE REVIEW

**Comment by xenolog** [comment]
А вы уверены, что к это 6-му числу акуально и успеет протестироваться?

**Comment by xdel** [comment]
Please mind, this not for merge, but mostly as a working proof.

**Comment by plechenko** [comment]
Please prepare this PR for merge into master

**Comment by xdel** [comment]
It`s time for merge

**Pull request closed without merging**
