### PR TITLE
Set partition GUID code when specified

### PR DESCRIPTION
**Pull request by rmoe**
Fixes PRD-2315.

Depends on https://review.openstack.org/#/c/52730/

### CODE REVIEW

**Comment by angdraug** [comment]
+1

**Comment by aglarendil** [comment]
Could you please rewrite this code to use parted instead of sgdisk because there is no gdisk package in centos vanilla repo

**Comment by angdraug** [comment]
Has to be gdisk: parted doesn't allow to specify arbitrary GPT partition type GUIDs.

**Comment by angdraug** [comment]
Nailgun side of this change:
https://review.openstack.org/#/c/52730/

**Comment by angdraug** [comment]
Tested on Centos and Ubuntu, passed.

**Comment by aglarendil** [comment]
+2

**Pull request merged**
