### PR TITLE
Grizzly

### PR DESCRIPTION
**Pull request by demofly**
Introducing a public grizzly repo from cloud-archive. Disabled a wrong mirantis repo for grizzly.

### CODE REVIEW

**Comment by xdel** [comment]
Will be merged along with the ovs-quantum-cleanup quirk.

**Comment by xdel** [comment]
Since we have a different thoughts on this patchset, please add proper apt-pin and change mirror to the http://download.mirantis.com/precise-fuel-grizzly/ and appropriate key. Push request will be fulfilled as soon as both(repo from my side and those fixes from yours) tasks compete.

**Comment by demofly** [comment]
Fixed apt::pins and outdated repos

**Comment by xdel** [comment]
Can you please check that the cobbler adding gpg key for puppetlabs properly in spare time?

**Comment by xdel** [comment]
Also please add quantum-ovs-cleanup package to the appropriate list in the puppet manifest.

**Comment by demofly** [comment]
Cancelling the request according to the freeze of the branch

**Pull request closed without merging**
