### PR TITLE
Use file_system field from fixture when formatting partitions

### PR DESCRIPTION
**Pull request by rmoe**

### CODE REVIEW

**Comment by angdraug** [comment]
+1

**Comment by aglarendil** [comment]
Vladimir K., review please.

**Comment by kozhukalov** [comment]
+1 but line 243 needs to be modified in order to meet "file_system" field set in nailgun

**Comment by angdraug** [comment]
Updated per code review, please confirm and merge.

**Comment by aglarendil** [comment]
+1
Vova K. please comment

**Comment by kozhukalov** [comment]
+1

**Pull request merged**
