### PR TITLE
glance image cache cleaning prd1115

### PR DESCRIPTION
**Pull request by kozhukalov**

### CODE REVIEW

**Comment by mihgen** [comment]
Vladimir, why did you close this pull request?
Please always specify comment / clear reason, links, etc.
Corresponding ticket: https://mirantis.jira.com/browse/PRD-1115

**Comment by aglarendil** [comment]
Code looks clean. +1. Waiting for test results.

**Comment by mihgen** [comment]
It obviously needs reopen as you closed it without merge.

**Comment by angdraug** [comment]
Rebased and resubmitted in #616.

**Pull request closed without merging**
