### PR TITLE
Fixup some un-needed string interpolations

### PR DESCRIPTION
**Pull request by xarses**
Removes some unnecessary string interpolations and adds line breaks

Fix horizon string interpolation
Fix l23network string interpolation
Fix quantum string interpolation

### CODE REVIEW

**Comment by mihgen** [comment]
+1. Passes CentOS deployment of controller,compute,cinder on 129th ISO

**Comment by aglarendil** [comment]
this is just simple lighweight fix. no need to merge it in this release

**Comment by dmitryilyin** [comment]
Looks nice but will become PITA for those who will rebse their branches on top of it.

**Comment by mihgen** [comment]
rebase needed

**Comment by aglarendil** [comment]
+2

**Pull request merged**
